/// <reference types="cypress" />

describe('GPI Portal Dev Pending Receipt - Test Approve Reject', () => {
  beforeEach(() => {
      cy.visit('https://portal-dev.gpi.id/launch')
      cy.wait(1000)
      cy.get('#__BVID__12').type('arlingga.wirawan@gpi.id')
      cy.wait(1000)
      cy.get('#input-2').type('Gpi76!!', {delay: 100})
      cy.wait(1000)
      cy.get("[type='submit']").click()
      cy.wait(3000)
      cy.get("[alt='In App Scan']").click()
      cy.wait(3000)
    })
    it('Test Approve 1st row', () => {
      cy.get("[class='w50']").contains('1').click()
      cy.wait(2000)
      cy.get('.item').contains('Merchant').click({ force: true })
      cy.wait(2000)
      cy.get('.item').contains('Adidas').click({force:true})
      cy.wait(2000)
      cy.get('.item').contains('grand indonesia').click({force:true})
      cy.wait(2000)
      cy.get("[class='vdatetime']").click()
      cy.wait(1000)
      cy.get('div.vdatetime-calendar__month__day.vdatetime-calendar__month__day--selected').click()
      cy.get('div.vdatetime-popup__actions__button.vdatetime-popup__actions__button--confirm').click()
      cy.wait(1000)
      //if total has input by OCR
      cy.get("[class='form-control boxed text-14 is-600 text-dark text-right']").clear()
      cy.wait(1000)
      cy.get("[class='form-control boxed text-14 is-600 text-dark text-right']").type('30000')
      cy.wait(1000)
      cy.get('.btn-success').click()
    })

    it('Test Reject 2nd row', () => {
      cy.get("[class='w50']").contains('2').click()
      cy.wait(2000)
      cy.get('.item').contains('EDC').click({ force:true})
      cy.wait(2000)
      cy.get('.item').contains('Credit Card').click({ force:true})
      cy.wait(2000)
      cy.get('.item').contains('BCA').click({ force:true})
      cy.wait(2000)
      cy.get('.item').contains('KKULDAK').click({force:true})
      cy.wait(2000)
      cy.get('.item').contains('grand indonesia').click({force:true})
      cy.wait(2000)
      cy.get("[class='vdatetime']").click()
      cy.wait(2000)
      cy.get('div.vdatetime-calendar__month__day.vdatetime-calendar__month__day--selected').click()
      cy.get('div.vdatetime-popup__actions__button.vdatetime-popup__actions__button--confirm').click()
      cy.wait(1000)
      //if total has input by OCR
      cy.get("[class='form-control boxed text-14 is-600 text-dark text-right']").clear() 
      cy.wait(1000)
      cy.get("[class='form-control boxed text-14 is-600 text-dark text-right']").type('30000')
      cy.wait(1000)
      cy.get("[class='btn margin-y-8 padding-10 text-14 text-light with-shadow btn-danger']").click({force:true})
      cy.get('.item').contains('Merchant, Mall atau Outlet tidak terdaftar di GetPlus').click({force:true})
    })
  })